# Generated by Django 2.1.2 on 2018-11-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0003_attendee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='event_name',
            field=models.CharField(max_length=200),
        ),
    ]
