# Generated by Django 2.1.2 on 2018-11-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0004_comment_approved'),
        ('eventmanager', '0006_attendee_user_name'),
    ]

    operations = [
    ]
